### ISSUE TITLE
Incorrect answer

### ISSUE THREAD

**Issue by jaroslawroszyk** [rabuf/advent-of-code#3]
https://github.com/rabuf/advent-of-code/blob/0da7f3196462a07396a10095fa690f3ba0dbfc57/2022/cpp/main.cpp

On line: 
std::nth_element(elves.begin(), elves.begin()+2, elves.end(), std::greater{});

should be: 
std::nth_element(elves.begin(), elves.begin(), elves.end(), std::greater{});

**Comment by rabuf** [comment]
I left that line intact but changed my part 1 answer to be the max of the first two elements.

https://github.com/rabuf/advent-of-code/blob/5a77f499339a11fb9410f02e1445163610a6f754/2022/cpp/main.cpp#L16-L19

This lets me perform `nth_element` once (for both parts). It has the effect of partitioning the vector so the first two elements will be the largest and second largest, just not always in order. It happened on my input that they ended up in the correct order but this version is more general.
